stages:
  - build
  - move
  - deploy

default:
  tags:
    - pet

build-job:
  stage: build
  script: "mvn package"

move-job:
  stage: move
  script: "cp target/petclinic.war /opt/tomcat/webapps"

deploy-prod:
  stage: deploy
  script: 
    - "/opt/tomcat/bin/catalina.sh" 
    - "run"
