stages:
  - build
  - move
  - deploy

default:
  tags:
    - pet

build-job:
  stage: build
  script: "mvn package"
  artifacts:
    paths:
      - "petclinic.war"    

move-job:
  stage: move
  script: "mv /opt/tomcat/webapps"

deploy-prod:
  stage: deploy
  script: "/opt/tomcat/bin/catalina.sh run"
