stages:
  - build
  - move
  - deploy

default:
  tags:
    - pet

build-job:
  stage: build
  script: "mvn package"
  artifacts:
    name: "petclinic" 
    paths:
      - "target/*.war"    

move-job:
  stage: move
  artifacts:
    name: "petclinic"
    paths: 
     - "target/*.war" 
  script: "cp target/petclinic.war /opt/tomcat/webapps"
    

deploy-prod:
  stage: deploy
  script: "/opt/tomcat/bin/catalina.sh run"
