- name: Install docker
  community.general.zypper: 
    name: docker
    state: latest
    update_cache: true

- name: start docker
  systemd:
    name: docker
    state: started 
    enabled: yes
    daemon_reload: yes
    
- name: docker user
  shell:
   cmd: usermod -aG docker adminuser

- name: Add user to docker group
  ansible.builtin.user:
    name: adminuser
    groups: docker
    append: true
  become: false

- name: restart docker
  shell:
    cmd: systemctl restart docker

- name: docker login
  shell: 
    cmd: docker login -u selmaboujenna -p dckr_pat_P9Uz9meMEr9x4DN95vcupaoRQbM