- name: Install docker
  community.general.zypper: 
    name: docker
    state: latest
    update_cache: true

- name: start docker
  systemd:
    name: docker
    state: started 
    enabled: yes
    daemon_reload: yes

- name: Ensure Docker group exists
  become: yes
  ansible.builtin.group:
    name: docker
    state: present
  register: docker_group

- name: Add User to docker group
  become: yes
  ansible.builtin.user:
    name: adminuser
    group: docker 
    append: true 

- name: refresh
  shell:
    cmd: id adminuser

- name: restart docker
  shell:
    cmd: systemctl restart docker

- name: Install websocket-client compatible with Python 3.6
  pip:
    name: websocket-client==0.57.0
    state: present

- name: install docker-py
  pip:
    name: docker-py
    state: present

- name: Include vault variables
  include_vars:
    file: vault.yml

- name: docker login
  docker_login:
    username: "{{docker_username}}"
    password: "{{docker_password}}"
                                        