- name: Install docker
  community.general.zypper: 
    name: docker
    state: latest
    update_cache: true

- name: start docker
  systemd:
    name: docker
    state: started 
    enabled: yes
    daemon_reload: yes

- name: Ensure Docker group exists
  become: yes
  ansible.builtin.group:
    name: docker
    state: present
  register: docker_group

- name: Add User to docker group
  become: yes
  ansible.builtin.user:
    name: adminuser
    group: docker 
    append: true 

- name: refresh
  shell:
    cmd: id adminuser

- name: restart docker
  shell:
    cmd: systemctl restart docker

- name: docker login
  shell: 
    cmd: docker login -u selmaboujenna -p dckr_pat_P9Uz9meMEr9x4DN95vcupaoRQbM