- name: importeer gpg key
  become: true
  ansible.builtin.rpm_key:
    state: present
    key: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"

- name: add elk repo
  become: true
  copy:
    dest: /etc/zypp/repos.d/elasticsearch.repo
    content: |
      [elasticsearch]
      name=Elasticsearch repository for 8.x packages
      baseurl=https://artifacts.elastic.co/packages/8.x/yum
      gpgcheck=1
      gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
      enabled=0
      autorefresh=1
      type=rpm-md

- name: enable repo
  become: true
  shell:
    cmd: zypper modifyrepo --enable elasticsearch

- name: installeer elastic
  become: true
  community.general.zypper:
    name: elasticsearch
    state: latest
    update_cache: yes

- name: permissions
  become: true   
  file:
    path: /etc/elasticsearch
    owner: adminuser
    group: users
    mode: 0755
  
- name: systemd reload
  become: true
  systemd:
    daemon_reload: yes
  
- name: start elasticsearch service
  become: true
  systemd:
    name: elasticsearch.service
    enabled: yes
    state: started

