- name: installeer kibana
  become: true
  community.general.zypper:
    name: kibana
    state: latest
    update_cache: yes

- name: permissions
  become: true   
  file:
    path: /etc/kibana
    owner: adminuser
    group: users
    mode: 0755

- name: template files
  become: true
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    mode: 0600

- name: systemd reload
  become: true
  systemd:
    daemon_reload: yes
  
- name: start kibana service
  become: true
  systemd:
    name: kibana.service
    enabled: yes
    state: started