- name: installeer logstash
  become: true
  community.general.zypper:
    name: logstash
    state: latest
    update_cache: yes

- name: permissions
  become: true   
  file:
    path: /etc/logstash
    owner: adminuser
    group: users
    mode: 0755

- name: systemd reload
  become: true
  systemd:
    daemon_reload: yes
  
- name: start logstash service
  become: true
  systemd:
    name: logstash.service
    enabled: yes
    state: started