---

- hosts: all
  become: true
  roles: 
  # - docker
  # - ansible
  # - maven
  # - tomcat
  # - gitlab
  # - jmeter
  # - selenium
  # - terraform
  # - java

- hosts: testingVM
  become: true
  roles: 
  - java
  - maven
    
    

    
