---

- hosts: all
  become: true
  # vars_files:
  #   - vars.yml
  # vars:
  #   ansible_ssh_private_key_file: "{{ key1 }}"
  roles: 
  - docker 
  # - ansible
  # - tomcat
  # - github-runner
  - java 
  - git 

- hosts: testingVM
  become: true
  roles: 
  - maven
  - jmeter

- hosts: acceptanceVM
  become: true
  roles:
  - selenium




  

  
    
    

    
