- hosts: productionVM
  become: true
  tasks:

  - name: pull image
    shell:
      cmd: docker pull selmaboujenna/provisioning1:latest

  - name: stop docker
    shell:
      cmd: docker stop $(docker ps -q)
    ignore_errors: yes

  - name: draai container
    shell:
      cmd: docker run -d -p 8080:8080 selmaboujenna/provisioning1:latest