---
- hosts: testingVM
  become: true

  tasks:

  - name: install git
    community.general.zypper:
      name: git
      state: present

  - name: Checkout repo
    ansible.builtin.git:
      repo: https://github.com/selmaboujenna/Githubpetclinic.git
      dest: /opt/temp
      version: pets
    ignore_errors: yes
      
  - name: maven build
    shell:
      chdir: /opt/temp
      cmd: mvn package

  - name: build image
    shell:
      chdir: /opt/temp
      cmd: docker build -t provisioning1 .

  - name: draai container
    shell:
      cmd: docker run -d -p 8080:8080 provisioning1

  - name: run jmeter test
    shell:
      cmd: /opt/apache-jmeter-5.6.3/bin/jmeter.sh -n -t /opt/temp/Loadtesting-petclinic.jmx -l test-result.jtl

  - name: adding tag
    shell:
      cmd: docker tag provisioning1 selmaboujenna/provisioning1

  - name: docker login
    shell: 
      cmd: docker login -u selmaboujenna -p dckr_pat_P9Uz9meMEr9x4DN95vcupaoRQbM

  - name: push image
    shell:
      cmd: docker push selmaboujenna/provisioning1 

    