---
- hosts: testingVM
  become: true

  tasks:

  - name: install git
    community.general.zypper:
      name: git
      state: present

  - name: Checkout repo
    ansible.builtin.git:
      repo: https://github.com/selmaboujenna/Githubpetclinic.git
      dest: /opt/temp
      
  - name: maven build
    shell:
      chdir: /opt/temp
      cmd: mvn package

  - name: build image
    shell:
      chdir: /opt/temp
      cmd: docker build -t provisioning1 .


     



#   - name: pull image
#     shell:
#       cmd: docker pull selmaboujenna/mywebapp3

 

#   # - name: restart container
#   #   shell:
#   #     cmd: systemctl restart docker

#   - name: draai container
#     shell:
#       cmd: docker run -d -p 8080:8080 selmaboujenna/mywebapp3



    