---
- hosts: testingVM
  become: true

  tasks:

  - name: maven build
    shell:
      chdir: /opt/temp
      cmd: mvn package

  - name: stop docker
    shell:
      cmd: docker stop $(docker ps -q)
    ignore_errors: yes

  - name: build image
    shell:
      chdir: /opt/temp
      cmd: docker build -t provisioning1 .

  - name: draai container
    shell:
      cmd: docker run -d -p 8080:8080 provisioning1

  - name: run jmeter test
    shell:
      cmd: /opt/apache-jmeter-5.6.3/bin/jmeter.sh -n -t /opt/temp/Loadtesting-petclinic.jmx -l test-result.jtl

  - name: adding tag
    shell:
      cmd: docker tag provisioning1 selmaboujenna/provisioning1

  - name: push image
    shell:
      cmd: docker push selmaboujenna/provisioning1 

    