- name: install selenium
  pip:
    name: selenium
    state: latest

- name: install pytest
  pip:
    name: pytest
    state: latest

- name: install chrome
  community.general.zypper:
    name: MozillaFirefox
    state: latest
    update_cache: true

- name: download driver
  get_url: 
    url: https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz
    dest: /opt

- name: unarchive driver
  unarchive:
    src: /opt/geckodriver-v0.30.0-linux64.tar.gz
    dest: /usr/bin
    remote_src: yes

- name: export path for chromedriver
  lineinfile:
    path: /home/adminuser/.bashrc
    state: present
    line: "{{item}}"
  with_items:
    - 'export PATH=${PATH}:/usr/bin/geckodriver'
  
- name: test
  shell:
    cmd: source /home/adminuser/.bashrc
