- name: install git
  community.general.zypper:
    name: git
    state: present

- name: Checkout repo
  ansible.builtin.git:
    repo: https://github.com/selmaboujenna/Githubpetclinic.git
    dest: /opt/temp
    version: pets
  ignore_errors: yes