on:
  push:
    branches:
      pets  
name: automate provisioning

jobs:
  build:
    runs-on: self-hosted
    steps:
    # - name: az login
    #   uses: azure/login@v1
    #   with:
    #     auth-type: IDENTITY
    #     client-id: ${{secrets.CLIENT_ID}}
    #     tenant-id: ${{secrets.TENANT_ID}}
    #     subscription-id: ${{secrets.SUBSCRIPTION_ID}}

    - name: initialize terraform
      run: terraform init
      working-directory: /home/adminuser/temp/terraform
    # - name: where am i
    #   run: terraform destroy --auto-approve
    #   working-directory: /home/adminuser/temp/terraform
    - name: create VMs
      run: terraform apply --auto-approve
      working-directory: /home/adminuser/temp/terraform
  
  configure:
    needs: build
    runs-on: self-hosted
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: maak een vault password file
      run: echo "${{secrets.VAULT_PASS}}" > /tmp/vault_pass.txt
    - name: run playbook
      run: ansible-playbook playbook.yml --vault-password-file /tmp/vault_pass.txt
      working-directory: /home/adminuser/temp/ansible-quickstart
    - name: verwijder vault pass
      run: rm /tmp/vault_pass.txt

  testing:
    needs: configure
    runs-on: self-hosted
    steps:
    - name: checkout repo 
      uses: actions/checkout@v4
    - name: run playbook for testingVM
      run: ansible-playbook testingVM.yml
      working-directory: /home/adminuser/temp/ansible-quickstart

  acceptance:
    needs: testing
    runs-on: self-hosted
    steps:
    - name: run playbook for acceptanceVM
      run: ansible-playbook acceptance.yml
      working-directory: /home/adminuser/temp/ansible-quickstart

  production:
    needs: acceptance
    runs-on: self-hosted
    steps:
      - name: run playbook for productionVM
        run: ansible-playbook productionVM
        working-directory: /home/adminuser/temp/ansible-quickstart

