on:
  push:
    branches:
      pets  
name: automate provisioning

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: wherami
      run: pwd
    
 
    # - name: az login
    #   uses: azure/login@v1
    #   with:
    #     auth-type: IDENTITY
    #     client-id: ${{secrets.CLIENT_ID}}
    #     tenant-id: ${{secrets.TENANT_ID}}
    #     subscription-id: ${{secrets.SUBSCRIPTION_ID}}

    - name: initialize terraform
      run: terraform init
      working-directory: terraform
    - name: where am i
      run: terraform destroy --auto-approve
      working-directory: terraform
    - name: create VMs
      run: terraform apply --auto-approve
      working-directory: terraform
  
  configure:
    needs: build
    runs-on: self-hosted
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: maak een vault password file
      run: echo "${{secrets.VAULT_PASS}}" > /tmp/vault_pass.txt
    - name: run playbook
      run: ansible-playbook playbook.yml --vault-password-file /tmp/vault_pass.txt
    - name: verwijder vault pass
      run: rm /tmp/vault_pass.txt

  testing:
    needs: configure
    runs-on: self-hosted
    steps:
    - name: checkout repo 
      run: actions/checkout@v4
    - name: run playbook for testingVM
      run: ansible-playbook testingVM.yml

  acceptance:
    needs: testing
    runs-on: self-hosted
    steps:
    - name: run playbook for acceptanceVM
      run: ansible-playbook acceptance.yml

  production:
    needs: acceptance
    runs-on: self-hosted
    steps:
      - name: run playbook for productionVM
        run: ansible-playbook productionVM

